using System;
using System.ComponentModel;
using TwinCAT.Ads;

namespace AdsSync.Mapping
{
    /// <summary>
    /// Provides an ADS mapper for reading the fields of an ADS structure into a .NET data object.
    /// </summary>
    /// <remarks>
    /// This class extends <see cref="AdsMapperBase"/> with the functionality required to receive 
    /// ADS device notifications for the individual fields of a structure. For each field, it stores 
    /// the field type and manages a corresponding ADS notification handle.
    ///
    /// Before notification handles can be created, the ADS variable handles must be generated by calling 
    /// <see cref="AdsMapperBase.GenerateVariableHandles(IAdsConnectAddress)"/>. Notifications are 
    /// registered with <see cref="NotificationSettings.ImmediatelyOnChange"/> and use the marshalled size 
    /// determined for the corresponding field.
    ///
    /// Derived classes or notification handlers are responsible for processing the received ADS values and 
    /// updating the mapped data object.
    /// </remarks>
    internal class AdsReadMapper : AdsMapperBase
    {
        #region properties
        /// <summary> The ADS device notification handles assigned to the individual fields </summary>
        public uint[] NotificationHandles { get; private set; }
        /// <summary> The type of the marshalled data structure </summary>
        public Type Type { get; private set; }
        #endregion

        #region constructors
        /// <summary>
        /// Initializes a new instance of this class.
        /// </summary>
        /// <param name="data"> The object whose data is to be read from the ADS client </param>
        /// <param name="structName"> The name of the ADS structure containing the data to be read </param>
        public AdsReadMapper(INotifyPropertyChanged data, string structName) : base(data, structName)
        {
            Type = DataAsMarshalledClass.GetType();
            NotificationHandles = new uint[VariableHandles.Length];
        }
        #endregion

        #region public methods
        /// <summary>
        /// Creates notification handles for each field in the marshalled data structure.
        /// </summary>
        /// /// <exception cref="ObjectDisposedException"> Thrown when this mapper has already been disposed. </exception>
        /// <exception cref="InvalidOperationException"> Thrown when the variable handles have not been created completely or when notification handles have already been created. </exception>
        public async Task GenerateNotificationHandlesAsync()
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            List<Exception> exceptions = [];
            if (adsClient is null)
            {
                throw new InvalidOperationException("Notification handle cannot be created before all variable handles have been created. Call GenerateVariableHandles() first.");
            }
            NotificationHandles = new uint[FieldInfos.Length];
            for (int i1 = 0; i1 < FieldInfos.Length; i1++)
            {
                using CancellationTokenSource cts = new(TimeSpan.FromSeconds(1));
                try
                {
                    ResultHandle resultHandle = await adsClient.AddDeviceNotificationAsync(StructName + "." + FieldInfos[i1].Name,
                                                                                           (int)Sizes[i1],
                                                                                           NotificationSettings.ImmediatelyOnChange,
                                                                                           null,
                                                                                           cts.Token);
                    if (resultHandle.Succeeded)
                    {
                        NotificationHandles[i1] = resultHandle.Handle;
                    }
                    else
                    {
                        exceptions.Add(new AdsErrorException("Error while creating a variable handle.", resultHandle.ErrorCode));
                    }
                }
                catch (OperationCanceledException)
                {
                    exceptions.Add(new TimeoutException($"Timeout while creating a variable handle."));
                }
            }
        }

        /// <summary>
        /// Deletes all notification handles created for each field in the marshalled data structure.
        /// </summary>
        /// <exception cref="ObjectDisposedException"> Thrown when this object is already disposed. </exception>
        /// <exception cref="ArgumentNullException"> Thrown when <paramref name="adsClient"/> is <see langword="null"/>. </exception>
        public async Task DeleteAllNotificationsHandlesAsync()
        {
            ObjectDisposedException.ThrowIf(disposed, this);
            ArgumentNullException.ThrowIfNull(adsClient);
            List<Exception> exceptions = [];
            for (int i = 0; i < NotificationHandles.Length; i++)
            {
                if (NotificationHandles[i] > 0)
                {
                    using CancellationTokenSource cts = new(TimeSpan.FromSeconds(1));
                    try
                    {
                        await adsClient.DeleteDeviceNotificationAsync(NotificationHandles[i], cts.Token);
                        NotificationHandles[i] = 0;
                    }
                    catch (OperationCanceledException)
                    {
                        exceptions.Add(new TimeoutException($"Timeout while deleting ADS notification handle {VariableHandles[i]}."));
                    }
                }
            }
            if (exceptions.Count > 0)
            {
                throw new AggregateException("One or more ADS notification handles could not be deleted.", exceptions);
            }
        }
        #endregion

        #region privates & protected methods
        /// <summary>
        /// Releases all resources used by this instance.
        /// </summary>
        /// <param name="disposing"> Disposes this istance if TRUE </param>
        protected override async ValueTask DisposeAsync(bool disposing)
        {
            if (disposed)
            {
                return;
            }
            if (disposing && adsClient is not null && adsClient.IsConnected && NotificationHandles is not null)
            {
                await DeleteAllNotificationsHandlesAsync();
            }
            await base.DisposeAsync(disposing);
            disposed = true;
        }
        #endregion
    }
}